[
	{
		"type":"heading",
		"value":"Datei"
	},
	{
		"type":"headingSmall",
		"value":"Speicherort:"
	},
	{
		"type":"text",
		"value":"%!#|params|#!%"
	},
	{
		"type":"input",
		"value":"%!#|params|#!%",
		"visible":"away",
		"name":"file"
	},
	{ "type":"nl" }, { "type":"nl" },
	{
		"type":"button",
		"value":"Herrunterladen",
		"click":"openMedia('file','%!#|params|#!%')"
	},
	{
		"type":"submit",
		"value":"Ordner erstellen"
	}
]